config/routes.rb
RecetarioMobile::Application.routes.draw do
  
  root 'recipes#index'
  resources :recipes
  get 'recipes/toggle_favorito/:id' => 'recipes#toggle_favorito', as: :toggle_favorito
  get '/galeria' => 'recipes#galeria', as: :galeria

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader
	default_scope {order("nombre COLLATE NOCASE ASC")}
  
	scope :favoritos, ->(fav = nil) {fav === 'true' ? where(favorito: true) : all}
	scope :galeria, -> (ingrediente = nil) { where( "ingrediente_principal =?" , ingrediente)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/recipes_controller.rb
require 'tempfile'
require 'fileutils'
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :toggle_favorito]
  after_action :recarga_manifest, only: [:create, :toggle_favorito]
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.favoritos(params[:favoritos])
  end
  
  def galeria
	@recipes = Recipe.galeria(params[:ingrediente])
  end
  # GET /recipes/1
  # GET /recipes/1.json
  def show
		
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end
  def toggle_favorito
    @recipe.favorito = !@recipe.favorito
    @recipe.save
    respond_to do |format|  
      format.html { redirect_to :back}
      format.js
    end
  end
  # POST /recipes
  
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:imagen, :descripcion, :ingrediente_principal, :dificultad, :tiempo, :ingredientes, :nombre, :plato)
    end
	
	def recarga_manifest
      path = 'public/appoffline.appcache'
      temp_file = Tempfile.new('appoffline.appcache')
      begin
        temp_file.write("CACHE MANIFEST\n")
        temp_file.write("# v #{Time.now.to_i}\n")
        f = File.open(path, 'r')
        2.times {f.gets}
        f.each_line do |line|
          temp_file.puts line
        end
        temp_file.rewind
        FileUtils.mv(temp_file.path, path)
      ensure
      temp_file.close
      temp_file.unlink
      end
	end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def fav(recipe)
   if recipe.favorito
    "minus"
   else
    "plus"
   end
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/appoffline.appcache">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>El Recetario</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= stylesheet_link_tag    "mi-tema", media: "all" %>
  <%= stylesheet_link_tag    "jquery.mobile.icons.min", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
	<div data-role="page">
		<div data-role="header" data-theme="a" data-position="fixed">
			
			<h1>El Recetario <div id="home"><%= link_to 'Home', recipes_path, class: "ui-btn ui-btn-icon-right ui-icon-home home", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false"%></div></h1>
			<%= yield :botones %>
		</div>
	
		<div role="main">
			<%= yield %>
		</div>

		<div data-role="footer" data-theme="a" data-position="fixed">
			<div id="galeria"><%= link_to 'Galeria', :galeria, class: "ui-btn ui-btn-icon-right ui-icon-grid", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false"%></div>
		</div>
	</div>
</body>
</html>

app/views/recipes/_form.html.erb
<% content_for :botones do %>            
	
	<%= link_to 'Atrás', recipes_path, "data-rel" => "back", class: "ui-btn ui-btn-icon-right ui-icon-back ", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
	<%= link_to 'Favoritos', recipes_path + '?favoritos=true', class: "ui-btn ui-btn-icon-right ui-icon-heart", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>

<% end %>
<%= form_for @recipe, html: {multipart: true, "data-ajax"=>"false"} do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ui-field-contain" data-role="fieldcontain">
    <%= f.label :imagen %>
    <%= f.file_field :imagen %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :ingrediente_principal %>
    <%= f.text_field :ingrediente_principal %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :dificultad %>
    <%= f.select :dificultad, [['dificultad',''],['fácil'],['media'],['dificil']] %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :tiempo %>
    <%= f.text_field :tiempo %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field ui-field-contain">
    <%= f.label :ingredientes %>
    <%= f.text_area :ingredientes %>
  </div>
  
  <div class="field ui-field-contain">
    <%= f.label :plato %>
    <%= f.select :plato, [['plato',''],['entrante'],['principal'],['postre']] %>
  </div>
  <div class="actions">
		 <%= f.submit 'Añadir Receta' %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/galeria.html.erb
<% content_for :botones do %>            
	<%= link_to 'Atrás', recipes_path, "data-rel" => "back", class: "ui-btn ui-btn-left ui-btn-icon-right ui-icon-back atras", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
	<%= link_to 'Favoritos', recipes_path + '?favoritos=true', class: "ui-btn ui-btn-icon-right ui-icon-heart",
	"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
<% end %>
<div class="ui-grid-a">	
	<div class="ui-block-a">
		<div class="ui-grid-a">	
		<div class="ui-block-a">
		
		<%= link_to 'Pescado', '/galeria?ingrediente=Pescado', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Carne', '/galeria?ingrediente=Carne', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Chocolate', '/galeria?ingrediente=Chocolate', class: "ui-btn ui-btn-icon-right ui-icon-grid", 			"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Verduras', '/galeria?ingrediente=Verduras', class: "ui-btn ui-btn-icon-right ui-icon-grid", 			"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Pollo', '/galeria?ingrediente=Pollo', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		</div>
		<div class="ui-block-b">
		<%= link_to 'Pasta', '/galeria?ingrediente=Pasta', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Legumbres', '/galeria?ingrediente=Legumbres', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Huevos', '/galeria?ingrediente=Huevos', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		<%= link_to 'Arroz', '/galeria?ingrediente=Arroz', class: "ui-btn ui-btn-icon-right ui-icon-grid",
		"data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
		</div>
		</div>
	</div>

	<div class="ui-block-b">
		<% @recipes.each do |recipe| %>
				<%= link_to recipe do  %>
        		<%= image_tag(recipe.imagen_url(:galeri), class: "imgGaleria" ) if recipe.imagen.present? %>
				 <% end %>
		<% end %>
	</div>
</div>

app/views/recipes/index.html.erb
<% content_for :botones do %>            
	<%= link_to 'Añadir', new_recipe_path, class: "ui-btn ui-btn-icon-right ui-icon-plus ", "data-inline" => "true", "data-role" => "button" %>
	<%= link_to 'Favoritos', recipes_path + '?favoritos=true', class: "ui-btn ui-btn-icon-right ui-icon-heart", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>

<% end %>
<ul data-role="listview" data-filter="true" data-filter-placeholder="¿Qué receta buscas?">
    <% @recipes.each do |recipe| %>
	<li class="ui-li-has-thumb">
	<%= link_to recipe do  %>
        <%= image_tag(recipe.imagen_url(:thumb)) if recipe.imagen.present? %>
	<h3><%= recipe.nombre %></h3>
	<ul>
		<li>Difitultad: <%= recipe.dificultad %></li>
		<li>Tiempo de preparación: <%= recipe.tiempo %></li>
		<li>Ingrediente Principal: <%= recipe.ingrediente_principal %></li>
		<li>Tipo de plato: <%= recipe.plato %></li>
	</ul>
	
	<% end %></li>
       
    <% end %>
</ul>

app/views/recipes/new.html.erb
<%= render 'form' %>

app/views/recipes/show.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag "recipes", media: "all" %>
<% end %>
<% content_for :botones do %>            
	
	<%= link_to 'Atrás', recipes_path, "data-rel" => "back", class: "ui-btn ui-btn-left ui-btn-icon-right ui-icon-back atras", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>
	<%= link_to 'Home', recipes_path, class: "ui-btn ui-btn-left ui-btn-icon-right ui-icon-home home2", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false"%>
	<%= link_to 'Favoritos', recipes_path + '?favoritos=true', class: "ui-btn ui-btn-right ui-btn-icon-right ui-icon-heart", "data-inline" => "true", "data-role" => "button", "data-ajax" => "false" %>

<% end %>

<div role="main" class="ui-content">
	<div class="ui-grid-a">
		<div class="ui-block-a"><%= image_tag(@recipe.imagen_url, :class => "imgreceta") if @recipe.imagen.present? %></div>
		<div class="ui-block-b"><ul class="claves" style="list-style:none;">
			<li><h4>Ingrediente principal:
			    <%= @recipe.ingrediente_principal %></h4>
			</li>
			<li><h4>Dificultad:
  			    <%= @recipe.dificultad %></h4>
			</li>
			<li><h4>Tiempo:</strong>
  			    <%= @recipe.tiempo %></h4>
			</li>
			<li><h4>Ingredientes:</strong>
  			    <%= @recipe.ingredientes %></h4>
			</li>
			<li><h4>Nombre:</strong>
  			    <%= @recipe.nombre %></h4>
			</li>
			<li><h4>Plato:</strong>
  			    <%= @recipe.plato %></h4>
			</li>
		</ul></div>
		
		<%= link_to "Añadir a favoritos", toggle_favorito_path(@recipe), {remote: true, id: "togglefav", class: "ui-btn ui-icon-#{fav(@recipe)} ui-btn-icon-top ui-btn-b ui-corner-all añadirfav", "data-ajax" => "false"} %>
		
	
		

		</div>
</div>

<p>
 <h3 class="preparacion">Preparación de la Receta</h3>
 <div style="margin-left: 2em; margin-right:2em;">
  <%= @recipe.descripcion %>
 </div>
</p>

app/views/recipes/toggle_favorito.js.erb
$('#togglefav').toggleClass( "ui-icon-plus ui-icon-minus");